### ISSUE TITLE
Too many java.io.IOException in PDFConverting process

### ISSUE THREAD

**Issue by benjaminpochat** [benjaminpochat/demos#28]
In the PDF converting process logs, we found many errors like this one, whereas the url is correct and can be downloaded successfully in a classic web browser.

020-01-01 21:11:52 ERROR PdfConverter:41 - An error occurs while converting http://mairie-larbresle.fr/public/files/0/mairie/conseil_municipal/comptes_rendus/2013/crcm09-07-2013_57fb82f263f07.pdf into text.
java.io.IOException: Error: End-of-File, expected line
        at org.apache.pdfbox.pdfparser.BaseParser.readLine(BaseParser.java:1123)
        at org.apache.pdfbox.pdfparser.COSParser.parseHeader(COSParser.java:2595)
        at org.apache.pdfbox.pdfparser.COSParser.parsePDFHeader(COSParser.java:2566)
        at org.apache.pdfbox.pdfparser.PDFParser.parse(PDFParser.java:219)
        at org.demos.pdfconverter.process.PdfConverter.getPDDocument(PdfConverter.java:50)
        at org.demos.pdfconverter.process.PdfConverter.convert(PdfConverter.java:36)
        at org.apache.kafka.streams.kstream.internals.AbstractStream.lambda$withKey$1(AbstractStream.java:103)
        at org.apache.kafka.streams.kstream.internals.KStreamMapValues$KStreamMapProcessor.process(KStreamMapValues.java:40)
        at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:117)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:201)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:180)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:133)
        at org.apache.kafka.streams.processor.internals.SourceNode.process(SourceNode.java:87)
        at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:366)
        at org.apache.kafka.streams.processor.internals.AssignedStreamsTasks.process(AssignedStreamsTasks.java:199)
        at org.apache.kafka.streams.processor.internals.TaskManager.process(TaskManager.java:420)
        at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:890)
        at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:805)
        at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:774)
2020-01-01 21:11:52 INFO  WebDocumentFilterByContent:18 - Document found at url http://mairie-larbresle.fr/public/files/0/mairie/conseil_municipal/comptes_rendus/2013/crcm09-07-2013_57fb82f263f07.pdf is dropped from the processing stream and won't be sent to the classification process, because its text content is null.

The solution might be given here :
https://stackoverflow.com/questions/50953924/pdfbox-ioexception-end-of-file-expected-line

**Comment by benjaminpochat** [comment]
The problem does not occur anymore since the solution mentionned above has been applied.
